### ISSUE TITLE
Version 0.3 to PyPi

### ISSUE THREAD

**Issue by mmaelicke** [cojacoo/rootwater#3]
Hey Conrad,

@svhoffmeister wanted to use your nice package, but unfortunately, the version `0.3` is not yet published on PyPi. Would be great if you pack and upload it there as well.
Best,
Mirko

**Comment by cojacoo** [comment]
Hi @mmaelicke and @svhoffmeister.
Thanks for pointing to this lack of updating. I just pushed the current version to PyPI.
Cheers.
Conrad
