### ISSUE TITLE
Test fails - with mixed-up lines

### ISSUE THREAD

**Issue by cojacoo** [cojacoo/rootwater#4]
In the recent updates, there appears to exist an issue which make the tests fail. Strangely, the first two lines of the array are twisted.

**Comment by svhoffmeister** [comment]
Hi Conrad,

I have a problem when trying to use [your data](https://github.com/cojacoo/rootwater/blob/master/docs/examples/soilmoisture.csv), which might be connected to the above. 

```python
import pandas as pd
import rootwater as rw
SM = pd.read_csv('ExConrad/soilmoisture.csv',index_col=0)
SM.index = pd.to_datetime(SM.index)
Sand_rwu,Sand_rwunn,Sand_nse = rw.rootwater.dfRWUc(SM.loc[:,SM.columns[:12]])
```

Screenshot of the error message:
![grafik](https://user-images.githubusercontent.com/50695639/94123043-94c68400-fe53-11ea-9493-8fe96b98bbee.png)

Any suggestions? 
Cheers Svenja

**Comment by cojacoo** [comment]
This error comes from a different issue and points to non-existent indices... I revised the functions in a new commit. Sorry for the inconvenience. Moreover, I checked on the algorithm and changed the test reference to a more advanced yet very similar reference. So the tests should succeed now...
